### ISSUE TITLE
Native type checks

### ISSUE THREAD

**Issue by TimothyGu** [jsdom/webidl-conversions#12]
Currently, many type checks are implemented as `instanceof`, which isn't exactly foolproof or standard-compliant. We could use [v8is](https://github.com/evanlucas/v8is) instead, but it is a native module which might pose installation difficulties.

**Comment by domenic** [comment]
I'm OK not being foolproof here. So I think Object.prototype.toString.call is probably the right way to go.

I know Error cannot be brand-checked in V8; although in theory trying to use the Error.prototype.stack getter should distinguish, it seems like that getter doesn't really exist in some brief testing.

I'm curious if there's an actual brand-check for the various typed-array types.

**Comment by TimothyGu** [comment]
> I know Error cannot be brand-checked in V8

There is [v8::Value::IsNativeError()](https://v8docs.nodesource.com/node-8.0/dc/d0a/classv8_1_1_value.html#acb34d79df34b47ae4c19a4458e381760) which seems to fill the bill.

> I'm curious if there's an actual brand-check for the various typed-array types.

Yup.

**Comment by domenic** [comment]
I meant from JavaScript, sorry.

**Comment by TimothyGu** [comment]
Ah. In that case, no.

**Comment by domenic** [comment]
The current status is that it is only [the typed array types](https://github.com/jsdom/webidl-conversions/blob/923d32089aac4e62c9f482f0b754d1cdff3c4f55/lib/index.js#L326-L339) which are tested using easily-forgeable means. They use `.constructor.name`. (They could alternately use `Symbol.toStringTag`, but I went with `.constructor.name` for now.)

This is a JS language limitation so this issue is mostly for tracking.

**Comment by ExE-Boss** [comment]
**SpiderMonkey**&nbsp;has&nbsp;`error.stack`&nbsp;implemented as&nbsp;a&nbsp;getter on&nbsp;the&nbsp;`Error`&nbsp;prototype, which&nbsp;throws for&nbsp;non‑`Error`&nbsp;objects and&nbsp;works&nbsp;cross‑realm.

**Comment by ExE-Boss** [comment]
I’m&nbsp;making the&nbsp;typed&nbsp;array&nbsp;conversions unforgeable&nbsp;in&nbsp;<https://github.com/jsdom/webidl-conversions/pull/22>.

**Comment by TimothyGu** [comment]
Looks like this has been fixed in #17 and #22. Time to close.
