### ISSUE TITLE
A little confused with converting symbol to 'DOMString'

### ISSUE THREAD

**Issue by hikerpig** [jsdom/webidl-conversions#14]
When unit testing with jest I get a TypeError, so I dug into [this line](https://github.com/jsdom/webidl-conversions/blob/074b6ec5371edb7f0275625702eda6aecf1c24af/lib/index.js#L227)

```
    if (typeof V === "symbol") {
        throw new TypeError(_("is a symbol, which cannot be converted to a string", opts));
    }
```

In [ecma-262 spec](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-symbol.prototype.tostring), there is `Symbol.prototype.toString()` method, it seems to me that convertion from     Symbol to String should not raise a Error.

Would you be kind enough to explain this?

**Comment by domenic** [comment]
There are many ways to convert things to a string. However, the Web IDL spec, which this library implements, chooses one of them: https://heycam.github.io/webidl/#es-DOMString step 2. That should provide the answer.

**Comment by hikerpig** [comment]
Thank you, I think maybe I should do a little patching an wrapping in my own code
