### ISSUE TITLE
Consider using BigInt to fix our 64-bit precision issues

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl-conversions#18]
We have a couple skipped tests, as discussed in the README at https://github.com/jsdom/webidl-conversions#a-note-on-the-long-long-types. Once the jsdom ecosystem moves to Node v10 minimum version, we could use BigInt to fix these.

**Comment by ExE-Boss** [comment]
There’s&nbsp;also&nbsp;<https://github.com/jsdom/webidl-conversions/pull/19>, which&nbsp;can be&nbsp;merged&nbsp;now.
