### ISSUE TITLE
Uncaught ReferenceError: SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by motla** [jsdom/webidl-conversions#31]
Hi! Thanks for your work on this library.

https://github.com/jsdom/webidl-conversions/blob/dd42044efbf4844c630270ce0d6b04a2a3d14a75/lib/index.js#L343-L344

On a lot of web browsers, SharedArrayBuffer is not defined so this line triggers an error as soon as the library is imported (https://caniuse.com/#search=sharedarraybuffer).

Why is that a global variable?

**Comment by TimothyGu** [comment]
We are listed to only support Node.js versions ≥ 10.4, all of which have `SharedArrayBuffer`:

https://github.com/jsdom/webidl-conversions/blob/dd42044efbf4844c630270ce0d6b04a2a3d14a75/package.json#L27-L29

**Comment by motla** [comment]
Well I assume this is for performance then, as globals are processed at import and not at each call.

I'll fork the project for my use. Thanks for your help.
