### ISSUE TITLE
SyntaxError: Unexpected {

### ISSUE THREAD

**Issue by ludwigschubi** [jsdom/webidl-conversions#33]
The try and catch syntax in index.js throws an error in my env:
```
...
} catch {
...
```
instead of 
```
...
} catch (e) {
...
```

**Comment by ludwigschubi** [comment]
Also see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

It defines error as non optional
```
[catch (exception_var) {
  catch_statements
}]
```

**Comment by domenic** [comment]
This is intentional. Your environment is not supported.

**Comment by ludwigschubi** [comment]
@domenic sorry if I don't get the full context of this, but what "bad" do these changes do? It's written like this in the Mozilla spec and apart from that only relevant to the parser and not the logic or?

**Comment by domenic** [comment]
Having to support old Node.js versions limits our ability to evolve the project. As it is a spare-time project we work on for fun, and we're not interested in legacy support, it's not something we'll be doing.

**Comment by domenic** [comment]
As for the outdated, unofficial, Mozilla documentation, that doesn't impact this project. We instead follow the specification at https://tc39.es/ecma262/, and the implementation in Node.js, where the variable is optional.

**Comment by ludwigschubi** [comment]
Great attitude you have there, very open

**Comment by ludwigschubi** [comment]
I added the support you just have to accept the pr

**Comment by ludwigschubi** [comment]
Go ahead and be stubborn about tiny issues 👍🏻
