### ISSUE TITLE
ReferenceError: Can't find variable: SharedArrayBuffer 

### ISSUE THREAD

**Issue by matiasmenares** [jsdom/webidl-conversions#37]
![image](https://user-images.githubusercontent.com/14056054/113492405-7b129300-94ad-11eb-92e6-000f5ffb6e94.png)

I have the 6.1.0 version but safari throw the error, in chrome work normally

if i comment the line lib/index.js line 348 work correctly

![image](https://user-images.githubusercontent.com/14056054/113492449-c6c53c80-94ad-11eb-8d98-fab6306691f1.png)

![image](https://user-images.githubusercontent.com/14056054/113492460-df355700-94ad-11eb-9dab-e594f7ddf653.png)

**Comment by alcheco** [comment]
Very interesting problem I have the same issue

**Comment by victorlin** [comment]
I have a similar issue (Safari only, works fine on Chrome):

> **ReferenceError: Can't find variable: BigInt**
> node_modules/webidl-conversions/lib/index.js:158

https://github.com/jsdom/webidl-conversions/blob/dd42044efbf4844c630270ce0d6b04a2a3d14a75/lib/index.js#L155-L158

**Comment by victorlin** [comment]
Seems like this is why: *https://github.com/magiclabs/magic-js/issues/131#issuecomment-689232720*

> ... runs on top of JavaScriptCore which doesn't have support yet for BigInt nor SharedArrayBuffer. In theory and assuming this is the root cause, the library might work just fine on Chrome but have similar issue on Safari which also runs on top of JavaScriptCore.

Until JavaScriptCore adds support for these, I'll have to avoid using `jsdom` in my project unless there is a workaround.

**Comment by matiasmenares** [comment]
@victorlin I had to do the same, i removed from project
