### ISSUE TITLE
Add SVG Conversions like SVGLength

### ISSUE THREAD

**Issue by Fuzzyma** [jsdom/webidl-conversions#4]
SVG bringts plenty new types which need a conversion.
e.g. SVGLength or SVGNumber.
Would be cool, to have something in place for that!

**Comment by TimothyGu** [comment]
`SVGLength` and `SVGNumber` are both interface types, and fall outside the scope of this module. They, along with other interface types, are for [webidl2js](https://github.com/jsdom/webidl2js) to handle.
